name: flutter_yandex_ads
description: Yandex Ads support for flutter applications.
version: 0.0.4+2
homepage: https://gitflic.ru/project/kovardin/flutter-yandex-ads

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  pigeon: ^1.0.19

flutter:
  plugin:
    platforms:
      android:
        package: ru.kovardin.flutter_yandex_ads
        pluginClass: FlutterYandexAdsPlugin
      ios:
        pluginClass: FlutterYandexAdsPlugin